### ISSUE TITLE
Switching Node.js runtime

### ISSUE THREAD

**Issue by Rlapham** [awslabs/landsat-on-aws#12]
AWS Lambda recently accepts Node v4.3. 
I am running Serverless v0.5.0 with Node v4.3 but I still get the following error: 

Serverless: us-west-2 ------------------------  
Serverless:   landsat-path: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

I've gone through some of the package.json files in hopes that changing the node versions there would help.

**Comment by jflasher** [comment]
Won't be able to update the code and test it for a bit, but if you change `nodesjs` to `nodejs4.3` in all the functions, that should do the trick. It's located in https://github.com/awslabs/landsat-on-aws/blob/master/restApi/landsat/path/s-function.json#L3 for each function. It could also be set globally I believe and removed from the individual functions.

**Comment by Rlapham** [comment]
That did the trick. After deploying in version 0.5.0 I recieved "Serverless Error: Runtime node js 4.3 is not supported!"

Deploying in version 0.5.5 worked. 

Thanks!
