### ISSUE TITLE
Inform in the documentation the serverless version being used 

### ISSUE THREAD

**Issue by fredliporace** [awslabs/landsat-on-aws#15]
If the latest serverless version is used an error is generated:
```
$ sls project init
 
  Serverless Error ---------------------------------------
 
  Serverless command "project" not found

  Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.11.5
     Serverless Version:     1.23.0
```
This command was deprecated with serverless 0.5

I've installed sls 0.5 instead and the command worked. It would be nice to know in the documentation which version is being used for development.

**Comment by jflasher** [comment]
Thanks @fredliporace, I'll add this to package.json now. Just a heads up if I was doing this today, I'd go with https://github.com/awslabs/serverless-application-model. May update this prototype in the future to go that route.
