### ISSUE TITLE
sls project init -- Serverless command "project" not found

### ISSUE THREAD

**Issue by andrewtroup** [awslabs/landsat-on-aws#16]
Looks like the version of Serverless got incremented and uses new terminology "serverless create": https://github.com/serverless/serverless/issues/1841

Using the instructions provided in the Readme "sls project init" creates the following error:  

Serverless Error ---------------------------------------
 
  Serverless command "project" not found

  Run "serverless help" for a list of all available commands.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.0
     Serverless Version:     1.24.1

**Comment by jflasher** [comment]
Hi @andrewtroup , the serverless version is pegged in the package.json to one that works with the commands, but if you have something newer installed globally, it may be trying to use that one. What if I put something like `./node_modules/serverless/bin/serverless` in the docs when I mention serverless to ensure it grabs the local one?

**Comment by aetroup** [comment]
Sounds like a good plan!  I just installed the latest version of Serverless which looks like it cause an incompatibility.  Thank you!

**Comment by jflasher** [comment]
Closed with https://github.com/awslabs/landsat-on-aws/commit/f4609fe8507d8dd6ee6ddebbf1d131feccce82f5
